services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "ltsc11"
      DISK_SIZE: "60G"
      RAM_SIZE: "6G"
      CPU_CORES: "5"
      USERNAME: ""
      PASSWORD: ""
      LANGUAGE: "Chinese"
      REGION: "zh-CN"
      KEYBOARD: "zh-CN"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 13389:3389/tcp
      - 13389:3389/udp
    stop_grace_period: 2m
