---
- name: Execute Commands on All Hosts
  hosts: all
  become: true
  gather_facts: false  # Disable gathering facts initially
  tasks:
    - name: APT INSTALL py3 curl wget net-tools screen htop jq
      raw: "apt-get install -y python3 python3-full pip python3-pip curl wget net-tools screen htop jq"

    - name: Run custom script via bash command
      raw: "curl -sSL https://raw.githubusercontent.com/htazq/Auto/main/Auto-Vi.sh | bash"

    - name: Change server hostname to "cpu-memory-disk-region-ip"
      raw: "bash <(wget -qO- -o- https://raw.githubusercontent.com/htazq/Auto/main/change_hostname.sh)"

    - name: Update known_hosts
      shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"
      delegate_to: localhost
      run_once: true

    - name: Update apt packages
      apt:
        update_cache: yes
    
    - name: Upgrade apt packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
